import type { Metadata } from "next";
import "./globals.css";
import { fontVariables } from "@/config/fonts";
import { ConvexClientProvider } from "./ConvexClientProvider.tsx";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import ClerkOfflineHandler from "@/components/clerk-offline-handler";

export const metadata: Metadata = {
  title: "Tars Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${fontVariables} antialiased`}>
          <ConvexClientProvider>
            <ThemeProvider attribute="class" enableSystem>
              {children}
              <ClerkOfflineHandler />
            </ThemeProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
